/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PascalFooter {
    'class': string;
    'copyright': string;
  }
}

declare global {


  interface HTMLPascalFooterElement extends Components.PascalFooter, HTMLStencilElement {}
  var HTMLPascalFooterElement: {
    prototype: HTMLPascalFooterElement;
    new (): HTMLPascalFooterElement;
  };
  interface HTMLElementTagNameMap {
    'pascal-footer': HTMLPascalFooterElement;
  }
}

declare namespace LocalJSX {
  interface PascalFooter {
    'class'?: string;
    'copyright'?: string;
  }

  interface IntrinsicElements {
    'pascal-footer': PascalFooter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pascal-footer': LocalJSX.PascalFooter & JSXBase.HTMLAttributes<HTMLPascalFooterElement>;
    }
  }
}


